packages:
  hal: github://wM-Bus/UltimateReader/packages/lilygo_t3_s3_hal.yaml@IoTLabs
  wmbus_gateway: github://wM-Bus/UltimateReader/packages/wmbus_gateway.yaml@IoTLabs

esphome:
  name: ultimatereader
  friendly_name: Ultimate Reader
  name_add_mac_suffix: true
  comment: Ultimate Reader
  project:
    name: wmbus.UltimateReader
    version: ${wmbus_gateway_version}

improv_serial:

esp32_improv:
  authorizer: none

logger:
  level: INFO
  logs:
    light: INFO
  baud_rate: 115200

ota:
  - platform: esphome

api:

dashboard_import:
  package_import_url: github://wM-Bus/UltimateReader/blueprints/UltimateReader.yaml@IoTLabs
  import_full_config: true

wmbus_radio:
  on_frame:
    - then:
        - logger.log:
            level: WARN
            format: "Meter ID: 0x%s"
            args: ["frame->meter_id().c_str()"]
        - logger.log:
            level: WARN
            format: "Frame: https://wmbusmeters.org/analyze/%s"
            args: ["frame->as_hex().c_str()"]
